In [1]:
import numpy as np 

In [2]:
## Bài 1
vetor = np.zeros(10)
print(vetor)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
## Bài 2
vector = np.zeros(10)
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [7]:
## Bài 3
vector = np.array(range(10,51,1))
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
## Bài 4
vector = np.array(range(1,13,1))
vector[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
## Baif 5
matrix = np.identity(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
## Bài 6
matrix = np.random.randint(low=1,high=101, size=(3,3))
matrix

array([[ 49,  77,  78],
       [100,  97,  84],
       [ 30,  37,  10]])

In [19]:
# Bài 7
matrix = np.random.randint(low=1,high=101, size=(10,10))
mt_min = np.amin(matrix)
mt_max = np.amax(matrix)
mt_min, mt_max

(2, 100)

In [21]:
# Bài 8
vector = np.random.randint(low=1,high=100,size=30)
np.average(vector)

58.13333333333333

In [49]:
# Bài 9
matrix = np.zeros((5,4))
matrix[:1 :] = 1
matrix[-1: :] = 1
matrix[:, :1] = 1
matrix[:, -1:] = 1
matrix

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [54]:
# Bài 10
matrix = np.random.randint(low=1,high=13,size=(6,6))
matrix = np.pad(matrix, pad_width=1, constant_values=0)
matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  3, 10, 12,  7,  7,  0],
       [ 0,  6, 10,  5,  4,  7,  2,  0],
       [ 0,  6,  5,  6,  7,  8,  1,  0],
       [ 0,  5,  7, 12,  8,  9, 12,  0],
       [ 0, 11,  9,  9,  4,  2,  3,  0],
       [ 0,  5,  8,  4,  9,  4,  3,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [58]:
# Bài 11
matrix = np.random.randint(low=1,high=5,size=(5,5))
triangle = np.tril(matrix,-1)
triangle

array([[0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [4, 1, 2, 0, 0],
       [1, 2, 3, 4, 0]])

In [65]:
# Bài 12
vecto=np.random.random(10)
vecto.sort()
vecto

array([0.02094537, 0.09780848, 0.18376142, 0.21801231, 0.32528076,
       0.4040059 , 0.42017216, 0.62494486, 0.69820933, 0.86273886])

In [66]:
# Bài 13
vt = np.random.randint(low=0,high=2,size=10)
vt

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0])